# Enable PMW3610 trackball sensor
CONFIG_SENSOR=y
CONFIG_PMW3610=y
CONFIG_PMW3610_CPI=600
CONFIG_PMW3610_FORCE_AWAKE=y
CONFIG_PMW3610_POLLING_RATE_250=y
CONFIG_INPUT=y
CONFIG_INPUT_PMW3610=n
CONFIG_ZMK_MOUSE=y
